{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.matrixidot.jsharp",
    "module": "gradle-plugin",
    "version": "0.2.0-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gradle-plugin-0.2.0-beta.jar",
          "url": "gradle-plugin-0.2.0-beta.jar",
          "size": 17652,
          "sha512": "247e74ef5c9ecb342c2fe9b3600c4c4e16659d3fd6ae276bd27c1bd6e2bc52f33b363102eb6a2d388d4e9743b0e3f3b4eb294798516fd299496d0203fbed4b9d",
          "sha256": "5d695a1cc680b4eb35e421507c7430d8466b16ed05c763235aad4509dd94f882",
          "sha1": "a244717e68b6e4fea8a7f9a849a8727d0aad8d1d",
          "md5": "2e9823349b23e5ac7e0014644c720f1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.matrixidot.jsharp",
          "module": "compiler",
          "version": {
            "requires": "0.2.0-beta"
          }
        },
        {
          "group": "io.github.matrixidot.jsharp",
          "module": "runtime",
          "version": {
            "requires": "0.2.0-beta"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.2.0-beta.jar",
          "url": "gradle-plugin-0.2.0-beta.jar",
          "size": 17652,
          "sha512": "247e74ef5c9ecb342c2fe9b3600c4c4e16659d3fd6ae276bd27c1bd6e2bc52f33b363102eb6a2d388d4e9743b0e3f3b4eb294798516fd299496d0203fbed4b9d",
          "sha256": "5d695a1cc680b4eb35e421507c7430d8466b16ed05c763235aad4509dd94f882",
          "sha1": "a244717e68b6e4fea8a7f9a849a8727d0aad8d1d",
          "md5": "2e9823349b23e5ac7e0014644c720f1e"
        }
      ]
    }
  ]
}
